language: node_js
script:
- npm run lint
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  on:
   repo: fac-unb/campus-online
   branch: master
  token:
    secure: yEtFydA10rarEtDAO3NoMaHZswm1MM3/NWEcUztU/LFe0Lp1g/vOZPCf34wqm4hhFYqIxnzyYLaR6eCCN9fWA+FZS2k0P3grA9CClQmDId/KZn3zbI5/PRDOfzThDyoRQxLVpuQnX29hjxpRogpVpBd/3BEetCWoM79ZHsWD2v3kNs63vdFpAaKqBKXICt8gD144zR8RIhBz1kIAKq7q5FGkQn5kneXb1C5o9Ld8UwxemdSh6koBI4gto0JyfHRQC4qBpcC+SM99szvOzB6Cylbk2knGGpBz9Q+oTgZge9KfDoGHE+Zquok7wlEDbxmh7JknJOhuDckr5H7sBCnQi2tXRawYioYa+tdxUbkoaEEqBlEbytzEYI+fFoZv/OiXxutlPT7e0Sk+NAu6eOq3dFvkL2VNzG9kscEY56cdY3QTmxakG7ZIoWuLGZFxeMSZ7BK7sBV3dlOlvara1G1IpwH+c324J1BNiEy0EKYiBrOkVZENv/iz9nrY5oA5zpVjWCIdwLtHKcELlK9nk8VoVkealHhroNDJskhpVZ2F7MsQZ8RLLUU8ocwhTVKlJoOyHL1QKaLlAYHTnjdL355W7ga9xYnTeJmW+HVphZkqN1kYCFK2typa46IXfsPMNH3MUnNZ6SG093pYdI+KthvMmjbqQqCXk+mCu3rE/LOHtNo=
