language: node_js
script:
- npm run lint && npm run run:travis
env:
  global:
  - REACT_APP_NETLIFY_CLIENT_ID: 07b77d90049181febc5fd7b52d9a873700248ee99bdb1ba594f7853b878e3c3e
  - secure: ZLZMF39kqoVbAQFMTu4oqXtWN/CbNZ+egYGty7VzYWlsh04J+680Co7LeEvCphQiKXha3iMoTnK8uXHavWs+WRIW0XZXRALpUKJhQPlhWD0oR8j22DIXMFlYu5ADN4/NdaZXZ+mzRC+p9QPfYLzMhG/F00mTXiLi0NHQrXMGwfZ6bHkV3Q8SLRBIjBFzElA6zKKcVIJApxqnIIHTYFIeqp3sQzTSB7uNjBOxyJWxbIIP5DyZ+e9iH9BDCtLAuqYl9VP6BbJb5hhY2Aok0gBeSLOFOh+kP+wgJIoSEBslIhwp3o8PudHWw1/sU3DSn0PuvsG0TTtgtkYbokst4WbFCqLWoQI76aJkctRzLNaM68u4EM4NiUh6ltO2HC7RbRzfs7j0O7UhjIu8yGpexKt54+V0d87JHf/88QZ4W1/oImyyUTXLrFrylKk6tkxMXReJGZo9NEo3ZGTjTsXnhOhzrCYXvn1P0bJN4Dx6z2/wHk7q5z6PQN+PwbjAOAy0LN46rUPNTnbMuwcXnSX5gFGK5bjdjhiWDyUpjPP4oDMLmS7EXTpB75qV0KBU4cxXlIesgx8iJegk7di4xmwZSZs49Yr7sSNuTBdkdYG7UyHwD/H769ortrL272Mk63IXwJDJXYmNztM7SeTrKuvpuhBMZujeTkoc819jgpV6XSyqnpw=
cache:
  yarn: true
  directories:
  - node_modules
  - packages/campus-enrollment-frontend/node_modules
  - packages/campus-enrollment-functions/node_modules
  - packages/campus-online-frontend/node_modules
  - packages/campus-online-functions/node_modules
git:
  depth: 1
notifications:
  email: false
