[build]
  command = "npm run build"
  publish = "packages/campus-online-frontend/public"
  functions = "packages/campus-online-functions/dist"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs8.10"

[[headers]]
  for = "/assets/fonts/*"
  [headers.value]
    Cache-Control = "public, max-age=86400"
