[build]
  command = "npm run run:netlify"
  publish = "packages/campus-online-frontend/public"
  functions = "packages/campus-online-functions/dist"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs8.10"
  REACT_APP_NETLIFY_CLIENT_ID = "07b77d90049181febc5fd7b52d9a873700248ee99bdb1ba594f7853b878e3c3e"

[[headers]]
  for = "/assets/fonts/*"
  [headers.value]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "http://campus.kunst.cloud/*"
  to = "https://campus.fac.unb.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://campus.kunst.cloud/*"
  to = "https://campus.fac.unb.br/:splat"
  status = 301
  force = true
