backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true

display_url: https://campus-online.netlify.com
media_folder: static/assets/images
public_folder: /assets/images

editor:
  preview: false

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    format: "yaml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "blog-post"}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Foto de Capa", name: "cover", widget: "image"}
      - {label: "Data de publicação", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Editoria", name: "editorial", widget: "relation", collection: "editorials", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Autor", name: "author", widget: "relation", collection: "authors", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Corpo", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}


  - name: "authors"
    label: "Autores"
    folder: "src/pages/authors"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{semester}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "author"}
      - {label: "Nome", name: "title", widget: "string", required: true}
      - {label: "Semestre no Campus (AAAA/S)", name: "semester", widget: "string", required: true, pattern: ['^\d{4}\/\d$', "Semestre fora do formato"]}
      - {label: "Foto (opcional)", name: "image", widget: "image", required: false}
      - {label: "Bio (opcional)", name: "body", widget: "markdown", required: false}

  - name: "editorials"
    label: "Editorias"
    folder: "src/pages/editorials"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Nome da Editoria", name: "title", widget: "string", required: true}
      - {label: "Cor (hexadecimal)", name: "color", widget: "string", required: true, pattern: ['^#(?:[0-9a-fA-F]{3}){1,2}$', "Cor Inválida"]}
      - {label: "Semestre (AAAA/S)", name: "semester", widget: "string", required: true, pattern: ['^\d{4}\/\d$', "Semestre fora do formato"]}
      - {label: "Descrição (opcional)", name: "description", widget: "text", required: false}



  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
