backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true

display_url: https://campus-online.netlify.com
media_folder: static/uploads
public_folder: /uploads

editor:
  preview: false

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    format: "yaml-frontmatter"
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "blog-post"}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Foto de Capa", name: "cover", widget: "image"}
      - {label: "Data de publicação", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Editoria", name: "editorial", widget: "relation", collection: "editorials", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Autor", name: "author", widget: "author", collection: "authors", searchFields: ["semester", "title"], required: false}
      - {label: "Corpo", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Destaque", name: "featured", widget: "boolean", default: false, required: false}


  - name: "authors"
    label: "Autores"
    folder: "src/pages/authors"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{semester}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "author"}
      - {label: "Nome", name: "title", widget: "string", required: true}
      - {label: "Semestre no Campus (AAAA/S)", name: "semester", widget: "string", required: true, pattern: ['^\d{4}\/\d$', "Semestre fora do formato"]}
      - {label: "Foto (opcional)", name: "image", widget: "image", required: false}
      - {label: "Bio (opcional)", name: "body", widget: "markdown", required: false}

  - name: "editorials"
    label: "Editorias"
    folder: "src/pages/editorials"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Nome da Editoria", name: "title", widget: "string", required: true}
      - {label: "Cor (hexadecimal)", name: "color", widget: "string", required: true, pattern: ['^#(?:[0-9a-fA-F]{3}){1,2}$', "Cor Inválida"]}
      - {label: "Semestre (AAAA/S)", name: "semester", widget: "string", required: true, pattern: ['^\d{4}\/\d$', "Semestre fora do formato"]}
      - {label: "Descrição (opcional)", name: "description", widget: "text", required: false}

  - name: "semesters"
    label: "Semestres"
    folder: "src/pages/semesters"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "semester"}
      - {label: "Semestre (AAAA/S)", name: "title", widget: "string", required: true, pattern: ['^\d{4}\/\d$', "Semestre fora do formato"]}
